INSERT INTO countries (country_code, country_name, capital, region)
VALUES
    ('AF', 'Afghanistan', 'Kabul', 'Asia'),
    ('AX', 'Åland Islands', 'Mariehamn', 'Europe'),
    ('AL', 'Albania', 'Tirana', 'Europe'),
    ('DZ', 'Algeria', 'Algiers', 'Africa'),
    ('AS', 'American Samoa', 'Pago Pago', 'Oceania'),
    ('AD', 'Andorra', 'Andorra la Vella', 'Europe'),
    ('AO', 'Angola', 'Luanda', 'Africa'),
    ('AI', 'Anguilla', 'The Valley', 'Americas'),
    ('AQ', 'Antarctica', '', 'Antarctic'),
    ('AG', 'Antigua and Barbuda', 'Saint John\'s', 'Americas'),
    ('AR', 'Argentina', 'Buenos Aires', 'Americas'),
    ('AM', 'Armenia', 'Yerevan', 'Asia'),
    ('AW', 'Aruba', 'Oranjestad', 'Americas'),
    ('AU', 'Australia', 'Canberra', 'Oceania'),
    ('AT', 'Austria', 'Vienna', 'Europe'),
    ('AZ', 'Azerbaijan', 'Baku', 'Asia'),
    ('BS', 'Bahamas', 'Nassau', 'Americas'),
    ('BH', 'Bahrain', 'Manama', 'Asia'),
    ('BD', 'Bangladesh', 'Dhaka', 'Asia'),
    ('BB', 'Barbados', 'Bridgetown', 'Americas'),
    ('BY', 'Belarus', 'Minsk', 'Europe'),
    ('BE', 'Belgium', 'Brussels', 'Europe'),
    ('BZ', 'Belize', 'Belmopan', 'Americas'),
    ('BJ', 'Benin', 'Porto-Novo', 'Africa'),
    ('BM', 'Bermuda', 'Hamilton', 'Americas'),
    ('BT', 'Bhutan', 'Thimphu', 'Asia'),
    ('BO', 'Bolivia', 'Sucre', 'Americas'),
    ('BA', 'Bosnia and Herzegovina', 'Sarajevo', 'Europe'),
    ('BW', 'Botswana', 'Gaborone', 'Africa'),
    ('BV', 'Bouvet Island', '', 'Antarctic'),
    ('BR', 'Brazil', 'Brasília', 'Americas'),
    ('IO', 'British Indian Ocean Territory', 'Diego Garcia', 'Africa'),
    ('VG', 'British Virgin Islands', 'Road Town', 'Americas'),
    ('BN', 'Brunei', 'Bandar Seri Begawan', 'Asia'),
    ('BG', 'Bulgaria', 'Sofia', 'Europe'),
    ('BF', 'Burkina Faso', 'Ouagadougou', 'Africa'),
    ('BI', 'Burundi', 'Gitega', 'Africa'),
    ('KH', 'Cambodia', 'Phnom Penh', 'Asia'),
    ('CM', 'Cameroon', 'Yaoundé', 'Africa'),
    ('CA', 'Canada', 'Ottawa', 'Americas'),
    ('CV', 'Cape Verde', 'Praia', 'Africa'),
    ('BQ', 'Caribbean Netherlands', 'Kralendijk', 'Americas'),
    ('KY', 'Cayman Islands', 'George Town', 'Americas'),
    ('CF', 'Central African Republic', 'Bangui', 'Africa'),
    ('TD', 'Chad', 'N\'Djamena', 'Africa'),
    ('CL', 'Chile', 'Santiago', 'Americas'),
    ('CN', 'China', 'Beijing', 'Asia'),
    ('CX', 'Christmas Island', 'Flying Fish Cove', 'Oceania'),
    ('CC', 'Cocos(Keeling) Islands', 'West Island', 'Oceania'),
    ('CO', 'Colombia', 'Bogotá', 'Americas'),
    ('KM', 'Comoros', 'Moroni', 'Africa'),
    ('CK', 'Cook Islands', 'Avarua', 'Oceania'),
    ('CR', 'Costa Rica', 'San José', 'Americas'),
    ('HR', 'Croatia', 'Zagreb', 'Europe'),
    ('CU', 'Cuba', 'Havana', 'Americas'),
    ('CW', 'Curaçao', 'Willemstad', 'Americas'),
    ('CY', 'Cyprus', 'Nicosia', 'Europe'),
    ('CZ', 'Czechia', 'Prague', 'Europe'),
    ('DK', 'Denmark', 'Copenhagen', 'Europe'),
    ('DJ', 'Djibouti', 'Djibouti', 'Africa'),
    ('DM', 'Dominica', 'Roseau', 'Americas'),
    ('DO', 'Dominican Republic', 'Santo Domingo', 'Americas'),
    ('CD', 'DR Congo', 'Kinshasa', 'Africa'),
    ('EC', 'Ecuador', 'Quito', 'Americas'),
    ('EG', 'Egypt', 'Cairo', 'Africa'),
    ('SV', 'El Salvador', 'San Salvador', 'Americas'),
    ('GQ', 'Equatorial Guinea', 'Malabo', 'Africa'),
    ('ER', 'Eritrea', 'Asmara', 'Africa'),
    ('EE', 'Estonia', 'Tallinn', 'Europe'),
    ('SZ', 'Eswatini', 'Mbabane', 'Africa'),
    ('ET', 'Ethiopia', 'Addis Ababa', 'Africa'),
    ('FK', 'Falkland Islands', 'Stanley', 'Americas'),
    ('FO', 'Faroe Islands', 'Tórshavn', 'Europe'),
    ('FJ', 'Fiji', 'Suva', 'Oceania'),
    ('FI', 'Finland', 'Helsinki', 'Europe'),
    ('FR', 'France', 'Paris', 'Europe'),
    ('GF', 'French Guiana', 'Cayenne', 'Americas'),
    ('PF', 'French Polynesia', 'Papeetē', 'Oceania'),
    ('TF', 'French Southern and Antarctic Lands', 'Port-aux-Français', 'Antarctic'),
    ('GA', 'Gabon', 'Libreville', 'Africa'),
    ('GM', 'Gambia', 'Banjul', 'Africa'),
    ('GE', 'Georgia', 'Tbilisi', 'Asia'),
    ('DE', 'Germany', 'Berlin', 'Europe'),
    ('GH', 'Ghana', 'Accra', 'Africa'),
    ('GI', 'Gibraltar', 'Gibraltar', 'Europe'),
    ('GR', 'Greece', 'Athens', 'Europe'),
    ('GL', 'Greenland', 'Nuuk', 'Americas'),
    ('GD', 'Grenada', 'St. George\'s', 'Americas'),
    ('GP', 'Guadeloupe', 'Basse-Terre', 'Americas'),
    ('GU', 'Guam', 'Hagåtña', 'Oceania'),
    ('GT', 'Guatemala', 'Guatemala City', 'Americas'),
    ('GG', 'Guernsey', 'St. Peter Port', 'Europe'),
    ('GN', 'Guinea', 'Conakry', 'Africa'),
    ('GW', 'Guinea-Bissau', 'Bissau', 'Africa'),
    ('GY', 'Guyana', 'Georgetown', 'Americas'),
    ('HT', 'Haiti', 'Port-au-Prince', 'Americas'),
    ('HM', 'Heard Island and McDonald Islands', '', 'Antarctic'),
    ('HN', 'Honduras', 'Tegucigalpa', 'Americas'),
    ('HK', 'Hong Kong', 'City of Victoria', 'Asia'),
    ('HU', 'Hungary', 'Budapest', 'Europe'),
    ('IS', 'Iceland', 'Reykjavik', 'Europe'),
    ('IN', 'India', 'New Delhi', 'Asia'),
    ('ID', 'Indonesia', 'Jakarta', 'Asia'),
    ('IR', 'Iran', 'Tehran', 'Asia'),
    ('IQ', 'Iraq', 'Baghdad', 'Asia'),
    ('IE', 'Ireland', 'Dublin', 'Europe'),
    ('IM', 'Isle of Man', 'Douglas', 'Europe'),
    ('IL', 'Israel', 'Jerusalem', 'Asia'),
    ('IT', 'Italy', 'Rome', 'Europe'),
    ('CI', 'Ivory Coast', 'Yamoussoukro', 'Africa'),
    ('JM', 'Jamaica', 'Kingston', 'Americas'),
    ('JP', 'Japan', 'Tokyo', 'Asia'),
    ('JE', 'Jersey', 'Saint Helier', 'Europe'),
    ('JO', 'Jordan', 'Amman', 'Asia'),
    ('KZ', 'Kazakhstan', 'Nur-Sultan', 'Asia'),
    ('KE', 'Kenya', 'Nairobi', 'Africa'),
    ('KI', 'Kiribati', 'South Tarawa', 'Oceania'),
    ('XK', 'Kosovo', 'Pristina', 'Europe'),
    ('KW', 'Kuwait', 'Kuwait City', 'Asia'),
    ('KG', 'Kyrgyzstan', 'Bishkek', 'Asia'),
    ('LA', 'Laos', 'Vientiane', 'Asia'),
    ('LV', 'Latvia', 'Riga', 'Europe'),
    ('LB', 'Lebanon', 'Beirut', 'Asia'),
    ('LS', 'Lesotho', 'Maseru', 'Africa'),
    ('LR', 'Liberia', 'Monrovia', 'Africa'),
    ('LY', 'Libya', 'Tripoli', 'Africa'),
    ('LI', 'Liechtenstein', 'Vaduz', 'Europe'),
    ('LT', 'Lithuania', 'Vilnius', 'Europe'),
    ('LU', 'Luxembourg', 'Luxembourg', 'Europe'),
    ('MO', 'Macau', '', 'Asia'),
    ('MG', 'Madagascar', 'Antananarivo', 'Africa'),
    ('MW', 'Malawi', 'Lilongwe', 'Africa'),
    ('MY', 'Malaysia', 'Kuala Lumpur', 'Asia'),
    ('MV', 'Maldives', 'Malé', 'Asia'),
    ('ML', 'Mali', 'Bamako', 'Africa'),
    ('MT', 'Malta', 'Valletta', 'Europe'),
    ('MH', 'Marshall Islands', 'Majuro', 'Oceania'),
    ('MQ', 'Martinique', 'Fort-de-France', 'Americas'),
    ('MR', 'Mauritania', 'Nouakchott', 'Africa'),
    ('MU', 'Mauritius', 'Port Louis', 'Africa'),
    ('YT', 'Mayotte', 'Mamoudzou', 'Africa'),
    ('MX', 'Mexico', 'Mexico City', 'Americas'),
    ('FM', 'Micronesia', 'Palikir', 'Oceania'),
    ('MD', 'Moldova', 'Chișinău', 'Europe'),
    ('MC', 'Monaco', 'Monaco', 'Europe'),
    ('MN', 'Mongolia', 'Ulan Bator', 'Asia'),
    ('ME', 'Montenegro', 'Podgorica', 'Europe'),
    ('MS', 'Montserrat', 'Plymouth', 'Americas'),
    ('MA', 'Morocco', 'Rabat', 'Africa'),
    ('MZ', 'Mozambique', 'Maputo', 'Africa'),
    ('MM', 'Myanmar', 'Naypyidaw', 'Asia'),
    ('NA', 'Namibia', 'Windhoek', 'Africa'),
    ('NR', 'Nauru', 'Yaren', 'Oceania'),
    ('NP', 'Nepal', 'Kathmandu', 'Asia'),
    ('NL', 'Netherlands', 'Amsterdam', 'Europe'),
    ('NC', 'New Caledonia', 'Nouméa', 'Oceania'),
    ('NZ', 'New Zealand', 'Wellington', 'Oceania'),
    ('NI', 'Nicaragua', 'Managua', 'Americas'),
    ('NE', 'Niger', 'Niamey', 'Africa'),
    ('NG', 'Nigeria', 'Abuja', 'Africa'),
    ('NU', 'Niue', 'Alofi', 'Oceania'),
    ('NF', 'Norfolk Island', 'Kingston', 'Oceania'),
    ('KP', 'North Korea', 'Pyongyang', 'Asia'),
    ('MK', 'North Macedonia', 'Skopje', 'Europe'),
    ('MP', 'Northern Mariana Islands', 'Saipan', 'Oceania'),
    ('NO', 'Norway', 'Oslo', 'Europe'),
    ('OM', 'Oman', 'Muscat', 'Asia'),
    ('PK', 'Pakistan', 'Islamabad', 'Asia'),
    ('PW', 'Palau', 'Ngerulmud', 'Oceania'),
    ('PS', 'Palestine', 'Ramallah', 'Asia'),
    ('PA', 'Panama', 'Panama City', 'Americas'),
    ('PG', 'Papua New Guinea', 'Port Moresby', 'Oceania'),
    ('PY', 'Paraguay', 'Asunción', 'Americas'),
    ('PE', 'Peru', 'Lima', 'Americas'),
    ('PH', 'Philippines', 'Manila', 'Asia'),
    ('PN', 'Pitcairn Islands', 'Adamstown', 'Oceania'),
    ('PL', 'Poland', 'Warsaw', 'Europe'),
    ('PT', 'Portugal', 'Lisbon', 'Europe'),
    ('PR', 'Puerto Rico', 'San Juan', 'Americas'),
    ('QA', 'Qatar', 'Doha', 'Asia'),
    ('CG', 'Republic of the Congo', 'Brazzaville', 'Africa'),
    ('RE', 'Réunion', 'Saint-Denis', 'Africa'),
    ('RO', 'Romania', 'Bucharest', 'Europe'),
    ('RU', 'Russia', 'Moscow', 'Europe'),
    ('RW', 'Rwanda', 'Kigali', 'Africa'),
    ('BL', 'Saint Barthélemy', 'Gustavia', 'Americas'),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Jamestown', 'Africa'),
    ('KN', 'Saint Kitts and Nevis', 'Basseterre', 'Americas'),
    ('LC', 'Saint Lucia', 'Castries', 'Americas'),
    ('MF', 'Saint Martin', 'Marigot', 'Americas'),
    ('PM', 'Saint Pierre and Miquelon', 'Saint-Pierre', 'Americas'),
    ('VC', 'Saint Vincent and the Grenadines', 'Kingstown', 'Americas'),
    ('WS', 'Samoa', 'Apia', 'Oceania'),
    ('SM', 'San Marino', 'City of San Marino', 'Europe'),
    ('ST', 'São Tomé and Príncipe', 'São Tomé', 'Africa'),
    ('SA', 'Saudi Arabia', 'Riyadh', 'Asia'),
    ('SN', 'Senegal', 'Dakar', 'Africa'),
    ('RS', 'Serbia', 'Belgrade', 'Europe'),
    ('SC', 'Seychelles', 'Victoria', 'Africa'),
    ('SL', 'Sierra Leone', 'Freetown', 'Africa'),
    ('SG', 'Singapore', 'Singapore', 'Asia'),
    ('SX', 'Sint Maarten', 'Philipsburg', 'Americas'),
    ('SK', 'Slovakia', 'Bratislava', 'Europe'),
    ('SI', 'Slovenia', 'Ljubljana', 'Europe'),
    ('SB', 'Solomon Islands', 'Honiara', 'Oceania'),
    ('SO', 'Somalia', 'Mogadishu', 'Africa'),
    ('ZA', 'South Africa', 'Pretoria', 'Africa'),
    ('GS', 'South Georgia', 'King Edward Point', 'Antarctic'),
    ('KR', 'South Korea', 'Seoul', 'Asia'),
    ('SS', 'South Sudan', 'Juba', 'Africa'),
    ('ES', 'Spain', 'Madrid', 'Europe'),
    ('LK', 'Sri Lanka', 'Sri Jayawardenepura Kotte', 'Asia'),
    ('SD', 'Sudan', 'Khartoum', 'Africa'),
    ('SR', 'Suriname', 'Paramaribo', 'Americas'),
    ('SJ', 'Svalbard and Jan Mayen', 'Longyearbyen', 'Europe'),
    ('SE', 'Sweden', 'Stockholm', 'Europe'),
    ('CH', 'Switzerland', 'Bern', 'Europe'),
    ('SY', 'Syria', 'Damascus', 'Asia'),
    ('TW', 'Taiwan', 'Taipei', 'Asia'),
    ('TJ', 'Tajikistan', 'Dushanbe', 'Asia'),
    ('TZ', 'Tanzania', 'Dodoma', 'Africa'),
    ('TH', 'Thailand', 'Bangkok', 'Asia'),
    ('TL', 'Timor-Leste', 'Dili', 'Asia'),
    ('TG', 'Togo', 'Lomé', 'Africa'),
    ('TK', 'Tokelau', 'Fakaofo', 'Oceania'),
    ('TO', 'Tonga', 'Nuku\'alofa', 'Oceania'),
    ('TT', 'Trinidad and Tobago', 'Port of Spain', 'Americas'),
    ('TN', 'Tunisia', 'Tunis', 'Africa'),
    ('TR', 'Turkey', 'Ankara', 'Asia'),
    ('TM', 'Turkmenistan', 'Ashgabat', 'Asia'),
    ('TC', 'Turks and Caicos Islands', 'Cockburn Town', 'Americas'),
    ('TV', 'Tuvalu', 'Funafuti', 'Oceania'),
    ('UG', 'Uganda', 'Kampala', 'Africa'),
    ('UA', 'Ukraine', 'Kyiv', 'Europe'),
    ('AE', 'United Arab Emirates', 'Abu Dhabi', 'Asia'),
    ('GB', 'United Kingdom', 'London', 'Europe'),
    ('US', 'United States', 'Washington, D.C.', 'Americas'),
    ('UM', 'United States Minor Outlying Islands', 'Washington DC', 'Americas'),
    ('VI', 'United States Virgin Islands', 'Charlotte Amalie', 'Americas'),
    ('UY', 'Uruguay', 'Montevideo', 'Americas'),
    ('UZ', 'Uzbekistan', 'Tashkent', 'Asia'),
    ('VU', 'Vanuatu', 'Port Vila', 'Oceania'),
    ('VA', 'Vatican City', 'Vatican City', 'Europe'),
    ('VE', 'Venezuela', 'Caracas', 'Americas'),
    ('VN', 'Vietnam', 'Hanoi', 'Asia'),
    ('WF', 'Wallis and Futuna', 'Mata-Utu', 'Oceania'),
    ('EH', 'Western Sahara', 'El Aaiún', 'Africa'),
    ('YE', 'Yemen', 'Sana\'a', 'Asia'),
    ('ZM', 'Zambia', 'Lusaka', 'Africa'),
    ('ZW', 'Zimbabwe', 'Harare', 'Africa');
